/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xxseany (https://sketchfab.com/xxseany)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/woodland-shire-3d6c490b76b8430c924860aa183ac749
Title: Woodland Shire
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame, useThree} from '@react-three/fiber'
import woodlandShireScene from '/Users/ronvicernestcuevas/Downloads/Untitled/src/assets/3d/woodland_shire.glb'
import { a } from "@react-spring/three";
const WoodlandShire =(props) => {
  const woodlandShireRef = useRef()
  const { nodes, materials } = useGLTF(woodlandShireScene)
  return (
    <a.group ref={woodlandShireRef} {...props} >
        <mesh   
          geometry={nodes.Scene_Mesh_pasted__Grass_MAT_0.geometry}
          material={materials.pasted__Grass_MAT}
        />
        <mesh 
          geometry={nodes.Scene_Mesh_pasted__TrimSheet_MAT_0.geometry}
          material={materials.pasted__TrimSheet_MAT}
        />
        <mesh
          geometry={nodes.Scene_Mesh_pasted__Roof_MAT_0.geometry}
          material={materials.pasted__Roof_MAT}
        />
        <mesh
          geometry={nodes.Scene_Mesh_pasted__Cliff_MAT_0.geometry}
          material={materials.pasted__Cliff_MAT}
        />
        <mesh
          geometry={nodes.Scene_Mesh_pasted__Town_MAT1_0.geometry}
          material={materials.pasted__Town_MAT1}
        />
        <mesh
          geometry={nodes.Scene_Mesh_pasted__pasted__Grass_MAT_0.geometry}
          material={materials.pasted__pasted__Grass_MAT}
        />
    </a.group>
  )
}

useGLTF.preload('/woodland_shire.glb')

export default WoodlandShire